<?php

namespace scheduleIdentityManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * disciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class disciplineRepository extends EntityRepository
{
}
