<?php

namespace scheduleIdentityManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * leagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class leagueRepository extends EntityRepository
{
}
