<?php

namespace scheduleIdentityManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * roundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roundRepository extends EntityRepository
{
}
