<?php

namespace scheduleIdentityManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * roundGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roundGameRepository extends EntityRepository
{
}
