<?php

namespace scheduleIdentityManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * seasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seasonRepository extends EntityRepository
{
}
